/*
 * bank-mizrahi-calculator
 *
 * The API for Bank Mizrahi
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ModelApiResponse : IEquatable<ModelApiResponse>
    { 
        /// <summary>
        /// Gets or Sets Result
        /// </summary>

        [DataMember(Name="result")]
        public decimal? Result { get; set; }

        /// <summary>
        /// Gets or Sets StatusCode
        /// </summary>

        [DataMember(Name="statusCode")]
        public int? StatusCode { get; set; }

        /// <summary>
        /// Gets or Sets ErrorMsg
        /// </summary>

        [DataMember(Name="errorMsg")]
        public string ErrorMsg { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ModelApiResponse {\n");
            sb.Append("  Result: ").Append(Result).Append("\n");
            sb.Append("  StatusCode: ").Append(StatusCode).Append("\n");
            sb.Append("  ErrorMsg: ").Append(ErrorMsg).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ModelApiResponse)obj);
        }

        /// <summary>
        /// Returns true if ModelApiResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of ModelApiResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ModelApiResponse other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Result == other.Result ||
                    Result != null &&
                    Result.Equals(other.Result)
                ) && 
                (
                    StatusCode == other.StatusCode ||
                    StatusCode != null &&
                    StatusCode.Equals(other.StatusCode)
                ) && 
                (
                    ErrorMsg == other.ErrorMsg ||
                    ErrorMsg != null &&
                    ErrorMsg.Equals(other.ErrorMsg)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Result != null)
                    hashCode = hashCode * 59 + Result.GetHashCode();
                    if (StatusCode != null)
                    hashCode = hashCode * 59 + StatusCode.GetHashCode();
                    if (ErrorMsg != null)
                    hashCode = hashCode * 59 + ErrorMsg.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ModelApiResponse left, ModelApiResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ModelApiResponse left, ModelApiResponse right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
