/*
 * bank-mizrahi-calculator
 *
 * The API for Bank Mizrahi
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;
using IO.Swagger.Security;
using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;
using IO.Swagger.Services;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class CalculateApiController : ControllerBase
    { 
        /// <summary>
        /// Calculation of the values according to the arithmetic operation
        /// </summary>
        /// <response code="200">ok</response>
        /// <response code="400">Bad request.</response>
        /// <response code="401">Access token is missing or invalid.</response>
        /// <response code="404">Not Found.</response>
        /// <response code="5XX">Unexpected error.</response>
        [HttpPost]
        [Route("/RIKI09325_1/Mizrachi/1.0.0/calculateArithmeticOperation")]
        [Authorize(AuthenticationSchemes = BearerAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("CalculateArithmeticOperation")]
        [SwaggerResponse(statusCode: 200, type: typeof(ModelApiResponse), description: "ok")]
        public virtual IActionResult CalculateArithmeticOperation([FromBody] ApiRequest request)
        {
            return new ObjectResult(CalculateService.Calculate(request));
        }
    }
}
